apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting-service
  template:
    metadata:
      labels:
        app: greeting-service
    spec:
      containers:
      - name: greeting
        image: docker.io/vanukurilikhita/greeting-service:latest
        ports:
        - containerPort: 4001
---
apiVersion: v1
kind: Service
metadata:
  name: greeting-service
spec:
  selector:
    app: greeting-service
  ports:
  - port: 4001
    targetPort: 4001
  type: NodePort
